### ISSUE TITLE
Buffersize too small

### ISSUE THREAD

**Issue by schwinn** [jj-wohlgemuth/pyssc#2]
Hi, 

thanks for providing this library. I had a problem were the buffersize in the `ssc_device.py` was too small. If a query with a long answer is performed, parts of the answer will be returned in the answer of further queries. This was the case for me with queries to /osc/schema. Changing the buffersize to 512 solved the problem.

```python
    def send_ssc(self,
                 command: str,
                 interface: str = "%eth0",
                 buffersize: int = 512,
                 wait_time_seconds: float = .001,
                 port: int = 45):
        self.port = port
```

I have published a small [tool](https://github.com/schwinn/khtool) with which I can query my Neumann KH 80 loudspeakers.

Thanks,
Thorsten

**Comment by jj-wohlgemuth** [comment]
Hi Thorsten,

thank you for your feedback. The parameter 'buffersize' is a variable with a [default value ](https://www.tutorialspoint.com/default-arguments-in-python) of 64. You can set any other integer value.

I'll add an example script to illustrate the relation between buffersize, performance and maximum RX string length.

Would you allow me to add a slightly modified version of your khtool.py to the pyssc examples? I'd make sure to name you as the author in the file header of course.

Best regards

JJ

**Comment by schwinn** [comment]
Hi JJ,

ok, that makes sense. I'm not very skilled with python. I just pushed a new version of the tool a changed buffersize setting.

Feel free to add a changed version.

Best regards,
Thorsten

**Comment by schwinn** [comment]
Hi, 

there's no need for a sleep command in the send_ssc function. The socket read is blocking and waits until the data is received, no matter how big the buffer is. So it's fine to have a big buffer byy default. Please try the code from below. It's just setting the socket timeout and removing the sleep. This should not have an impact on short answers of the speaker.

Best regards,
Thorsten

```python
import socket
import time
import logging
from .Ssc_transaction import Ssc_transaction


class Ssc_device():
    """
    :param name: device name
    :param ip: ip address of ssc device

    .. code-block:: python
        :caption: todo

        >>> todo

    """
    def __init__(self,
                 name: str,
                 ip: str = None,
                 port: int = 45):
        self.name = name
        self.ip = ip
        self.socket = None
        self.port = port

    def connect(self, interface: str = "%eth0", port: int = 45):
        self.port = port
        self.socket = socket.create_connection((self.ip + interface, port))
        self.socket.setblocking(True)
        self.socket.settimeout(1)

    def disconnect(self):
        self.socket.close()

    def send_ssc(self,
                 command: str,
                 interface: str = "%eth0",
                 buffersize: int = 64,
                 wait_time_seconds: float = .001,
                 port: int = 45):
        self.port = port
        request_raw = f'{command}\r\n'.encode('utf-8')
        try:
            self.socket.sendto(request_raw, (self.ip + interface, self.port))
        except Exception as e:
            logging.warning('socket connection closed. Reopening. ' + str(e))
            self.connect(interface=interface, port=port)
            self.socket.sendto(request_raw, (self.ip + interface, self.port))
        data = self.socket.recv(buffersize)
        ssc_transaction = Ssc_transaction()
        ssc_transaction.TX = command
        ssc_transaction.RX = data.decode('utf-8')
        return ssc_transaction
```

**Comment by jj-wohlgemuth** [comment]
Thanks Thorsten - that makes a lot of sense. I ran some experiments this morning just to be sure and it looks like I can indeed drop wait_time_seconds and increase the default buffersize. Looks like the buffersize has no direct effect on the execution time.

```
buffersize: 32768
Execution time: 38 milliseconds

buffersize: 32768
Execution time: 47 milliseconds

buffersize: 512
Execution time: 56 milliseconds

buffersize: 512
Execution time: 42 milliseconds
```

I'll test and push the changes in the next days. You are also welcome to create a pull request if you feel like it.

**Comment by schwinn** [comment]
Hi JJ,

thanks for implemting the pull request. 

I wrote a test Python app for the macOS menu bar that uses the pyssc library to dim the speakers. For this i changed some socket calls in the library to catch exceptions and control the reconnect better. Now the app doesn't freeze as often and for a long time when a speaker is unreachable.

I still need to clean up the code a bit and test it further. If you are interested, I can send you the changes next week for review. I think a pull request is not the right way to discuss the changes.

Cheers,
Thorsten


![grafik](https://user-images.githubusercontent.com/138371/206526604-d72e2df3-4d33-4c5a-972a-57080907dec1.png)

**Comment by jj-wohlgemuth** [comment]
Sounds great - I'm very interested! You can PR or send me the changes. Looking forward to it.

**Comment by jj-wohlgemuth** [comment]
@schwinn - this might be interesting to you: https://github.com/jj-wohlgemuth/pyssc-level-controller
