### ISSUE TITLE
Demo commands not working

### ISSUE THREAD

**Issue by audafreak** [jj-wohlgemuth/pyssc#4]
I tried exactly according doc first 4 lines on Windows 10, Python 3.11, Idle. Problem on set_transaction:

**import pyssc as ssc
found_setup = ssc.scan()
device_1 = found_setup.ssc_devices[0]
_ssc_transaction = device_1.send_ssc('{"audio":{"out":{"mute":false}}}')_**
WARNING:root:socket connection closed. Reopening. 'NoneType' object has no attribute 'sendto'
Traceback (most recent call last):
File "C:\Python\P311\Lib\site-packages\pyssc\ssc_device.py", line 43, in send_ssc
self.socket.sendto(request_raw, (self.ip + interface, self.port))
AttributeError: 'NoneType' object has no attribute 'sendto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<pyshell#9>", line 1, in <module>
ssc_transaction = device_1.send_ssc('{"audio":{"out":{"mute":false}}}')
File "C:\Python\P311\Lib\site-packages\pyssc\ssc_device.py", line 46, in send_ssc
self.connect()
File "C:\Python\P311\Lib\site-packages\pyssc\ssc_device.py", line 28, in connect
self.socket = socket.create_connection((self.ip + interface, port))
File "C:\Python\P311\Lib\socket.py", line 826, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "C:\Python\P311\Lib\socket.py", line 961, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by jj-wohlgemuth** [comment]
Thank you for testing. That behavior makes sense. The method from_json() has no return so _found_setup_ can only be None. I'll fix it.

**Comment by jj-wohlgemuth** [comment]
Alright done 

https://github.com/jj-wohlgemuth/pyssc/commit/40cb5fa345b5897c6a187c44b48d97089e4c613f

![grafik](https://user-images.githubusercontent.com/52459869/210240437-d42a94bc-5cec-4569-96c0-8e46af8b5322.png)
